// Auto-generated by: npm run db:types
// Do not edit manually. Re-run after any migration change.
//
// If this file only has this placeholder, run:
//   npm run db:types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      allowed_emails: {
        Row: {
          email: string
        }
        Insert: {
          email: string
        }
        Update: {
          email?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          id: string
          display_name: string
          created_at: string
          can_create_voting_round: boolean
        }
        Insert: {
          id: string
          display_name: string
          created_at?: string
          can_create_voting_round?: boolean
        }
        Update: {
          id?: string
          display_name?: string
          created_at?: string
          can_create_voting_round?: boolean
        }
        Relationships: []
      }
      reactions_rounds: {
        Row: {
          id: string
          trip_id: string
          name: string | null
          created_at: string
          is_open: boolean
        }
        Insert: {
          id?: string
          trip_id: string
          name?: string | null
          created_at?: string
          is_open?: boolean
        }
        Update: {
          id?: string
          trip_id?: string
          name?: string | null
          created_at?: string
          is_open?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "reactions_rounds_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: false
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
        ]
      }
      reactions_round_suggestions: {
        Row: {
          reactions_round_id: string
          suggestion_id: string
        }
        Insert: {
          reactions_round_id: string
          suggestion_id: string
        }
        Update: {
          reactions_round_id?: string
          suggestion_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reactions_round_suggestions_reactions_round_id_fkey"
            columns: ["reactions_round_id"]
            isOneToOne: false
            referencedRelation: "reactions_rounds"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reactions_round_suggestions_suggestion_id_fkey"
            columns: ["suggestion_id"]
            isOneToOne: false
            referencedRelation: "suggestions"
            referencedColumns: ["id"]
          },
        ]
      }
      reactions: {
        Row: {
          reactions_round_id: string
          suggestion_id: string
          user_id: string
          score: number
          created_at: string
        }
        Insert: {
          reactions_round_id: string
          suggestion_id: string
          user_id: string
          score: number
          created_at?: string
        }
        Update: {
          reactions_round_id?: string
          suggestion_id?: string
          user_id?: string
          score?: number
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "reactions_reactions_round_id_fkey"
            columns: ["reactions_round_id"]
            isOneToOne: false
            referencedRelation: "reactions_rounds"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reactions_suggestion_id_fkey"
            columns: ["suggestion_id"]
            isOneToOne: false
            referencedRelation: "suggestions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reactions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      trips: {
        Row: {
          id: string
          name: string
          owner_id: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          owner_id: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          owner_id?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "trips_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      suggestions: {
        Row: {
          id: string
          trip_id: string
          created_by: string
          title: string
          description: string
          lat: number | null
          lng: number | null
          created_at: string
          author_label: string | null
          main_image_url: string | null
        }
        Insert: {
          id?: string
          trip_id: string
          created_by: string
          title: string
          description?: string
          lat?: number | null
          lng?: number | null
          created_at?: string
          author_label?: string | null
          main_image_url?: string | null
        }
        Update: {
          id?: string
          trip_id?: string
          created_by?: string
          title?: string
          description?: string
          lat?: number | null
          lng?: number | null
          created_at?: string
          author_label?: string | null
          main_image_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "suggestions_trip_id_fkey"
            columns: ["trip_id"]
            isOneToOne: false
            referencedRelation: "trips"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "suggestions_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Helper types
type Tables = Database["public"]["Tables"]
export type Profile = Tables["profiles"]["Row"]
export type Trip = Tables["trips"]["Row"]
export type Suggestion = Tables["suggestions"]["Row"]
export type ReactionsRound = Tables["reactions_rounds"]["Row"]
export type ReactionsRoundSuggestion = Tables["reactions_round_suggestions"]["Row"]
export type Reaction = Tables["reactions"]["Row"]
