-- Change reactions score from -1..2 to 1..5 (stars).
-- Migrate existing data: -1→1, 0→2, 1→3, 2→4
update public.reactions set score = score + 2 where score in (-1, 0, 1, 2);

-- Drop the existing score check (name is auto-generated by Postgres)
do $$
declare
  c name;
begin
  for c in
    select conname from pg_constraint
    where conrelid = 'public.reactions'::regclass and contype = 'c'
      and pg_get_constraintdef(oid) like '%score%'
  loop
    execute format('alter table public.reactions drop constraint %I', c);
  end loop;
end $$;

alter table public.reactions add constraint reactions_score_check check (score >= 1 and score <= 5);
